version: "3"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NAME=DEV ENV
    command: node app.js
