version: "3"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      - NAME=DEV ENV
    command: npm run dev
# volumes:
#   app_data:
#     driver: local
